services:
  redis:
    image: redis:7-alpine

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    env_file: .env
    ports:
      - "8123:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/init:/docker-entrypoint-initdb.d

  datafetch:
    build: ./datafetch
    env_file: .env
    volumes:
      - ./datafetch/app:/app
    stdin_open: true
    tty: true
    depends_on:
      - clickhouse
      - redis

volumes:
  clickhouse_data:
